### PR TITLE
fix NullPointerException

### PR DESCRIPTION
**Pull request by jishnu7**

### CODE REVIEW

**Comment by jishnu7** [comment]
Need to test it on device.

**Comment by rampr** [comment]
1. We should test it on device before merging
2. You can put it under try catch block also for extra safety ?

**Comment by jishnu7** [comment]
try catch is not needed.
Android documentation says "Returns a list of RunningAppProcessInfo records, or null if there are no running processes (it will not return an empty list)."

**Comment by rampr** [comment]
Looks good

**Pull request merged**
