### PR TITLE
Added gradle tranformation function for dynamic variables like transformXSL for xml files

### PR DESCRIPTION
**Pull request by CodeCombiner**
Formatted indentation to 2 spaces.

### CODE REVIEW

**Review by vivekb91 — APPROVED** [review]

**Comment by rampr** [comment]
@CodeCombiner Looks like the indentation has changed. Can you put it back please ?

**Comment by CodeCombiner** [comment]
@rampr , fixed. It was wrong IDE setting.

**Comment by rampr** [comment]
@CodeCombiner looks the whole build.js got changed from 2 to 4 spaces. Please look at diff

**Comment by CodeCombiner** [comment]
@rampr , fixed

**Review by rampr — APPROVED** [review]

**Pull request merged**
