### PR TITLE
Update libpng to 1.5.27

### PR DESCRIPTION
**Pull request by mit456**
Due to vulnerability in 1.5.9, Google's suggested version is 1.5.26

### CODE REVIEW

**Comment by jishnu7** [comment]
can we update to the latest version in 1.5 series?

**Comment by rampr** [comment]
1.5.27 is the latest version

**Comment by rampr** [comment]
@jishnu7 We should still merge this and check for 1.5.27 parallely.

**Comment by mit456** [comment]
Updated to 1.5.27

**Comment by rampr** [comment]
has to be tested

Have we tested on android 2.x, android 4.1 also ?

**Comment by mit456** [comment]
Tested in 4.1. Working

**Comment by zephyr2k** [comment]
LGTM

**Comment by sksethi25** [comment]
Looks gud to me

**Comment by rohanhc** [comment]
LGTM

**Comment by rampr** [comment]
We are removing support for 2.x series, so not testing for that version

**Pull request merged**
