### PR TITLE
Move icons from drawable to mipmap

### PR DESCRIPTION
**Pull request by rampr**
Modified to follow this -> https://developer.android.com/guide/practices/screens_support.html#support

---

This change is [Reviewable](https://reviewable.io/reviews/hashcube/native-android/5)

### CODE REVIEW

**Comment by bijoshtj** [comment]
:lgtm:

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/hashcube/native-android/5#-:-KQVLQPQnxCy1KzK3DYj:bnfp4nl)_

**Comment by bijoshtj** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/hashcube/native-android/5)_

**Comment by rohanhc** [comment]
:lgtm:

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/hashcube/native-android/5#-:-KQVLgqWso95Hd959xSk:bnfp4nl)_

**Comment by jishnu7** [comment]
LGTM

we should send this to  upstream.

**Comment by rampr** [comment]
will do that too

**Comment by sksethi25** [comment]
Awesome, Done

**Pull request merged**
